spring:
  datasource:
    url: jdbc:mysql://116.63.233.180:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: zxcvbnm1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      check-template-location: true
      encoding: UTF-8
      mode: HTML5
logging:
  level:
    com.example.mapper: debug
pagehelper:
  auto-dialect: true